### ISSUE TITLE
В синтакс-помощнике нет гл. функций для переменных среды

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScriptDocumenter#7]
[GlobalContext(Category = "Работа с переменными окружения")]
public class EnvironmentVariablesImpl : GlobalContextBase<EnvironmentVariablesImpl>

В синтакс-помощнике отсутствует данный гл. контекст.

**Comment by bambr1975** [comment]
http://oscript.io/syntax/page/%d0%a0%d0%b0%d0%b1%d0%be%d1%82%d0%b0%20%d1%81%20%d0%bf%d0%b5%d1%80%d0%b5%d0%bc%d0%b5%d0%bd%d0%bd%d1%8b%d0%bc%d0%b8%20%d0%be%d0%ba%d1%80%d1%83%d0%b6%d0%b5%d0%bd%d0%b8%d1%8f ?
